{% set version = '1.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gmwt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gMWT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gMWT/gMWT_{{ version }}.tar.gz
  sha256: 2a96272939fcdd094a14723ef63d72e26bf963d3ca33f8e036fd256ab66a67c7

build:
  number: 2
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-rcpp >=0.9.13
    - r-rcpparmadillo
    - r-clinfun
  run:
    - r-base
    - r-rcpp >=0.9.13
    - r-rcpparmadillo
    - r-clinfun

test:
  commands:
    - $R -e "library('gMWT')"           # [not win]
    - "\"%R%\" -e \"library('gMWT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gMWT
  license: GPL-2.0-or-later
  summary: Generalized Mann-Whitney type tests based on probabilistic indices and new diagnostic
    plots, for the underlying manuscript see Fischer, Oja (2015) <doi:10.18637/jss.v065.i09>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
